runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /assets
  static_dir: assets
  http_headers:
    Access-Control-Allow-Origin: "*"
- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest